In [1]:
import torch
# tensor is like numpy array

In [2]:
x = torch.arange(10) # create a row vector (tensor) 

In [3]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x.shape # shape

torch.Size([10])

In [5]:
x.reshape(2,5) # reshape; it is not a inplace operation

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
x.shape # x is not changed

torch.Size([10])

In [7]:
X = x.reshape(2,5)

In [8]:
X.shape

torch.Size([2, 5])

In [9]:
X.numel() # number of elements in a tensor

10

In [10]:
X

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
x.reshape(2,-1) # use -1 to specify the dimension implicitly

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# initialize tensor with zeros, ones
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.randn(3,4)

tensor([[ 1.3092, -0.2793,  0.1457, -0.8857],
        [ 0.5237,  0.2758, -0.3162, -0.3640],
        [ 0.2558,  1.1452, -1.7141,  0.0752]])

In [15]:
torch.zeros_like(X)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [16]:
torch.tensor([[1,2,3,4], [5,6,7,8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [17]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [18]:
# element-wise operation
# For functions that take two arrays as inputs, elementwise operations 
# apply some standard binary operator on each pair of corresponding 
# elements from the two arrays. We can create an elementwise function 
# from any function that maps from a scalar to a scalar.

In [19]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [20]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [21]:
x * y 

tensor([ 2.,  4.,  8., 16.])

In [22]:
x / y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [23]:
x ** y

tensor([ 1.,  4., 16., 64.])

In [24]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [25]:
# concatenate
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [26]:
torch.cat((X,Y),dim=0) # concatenate by row

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [27]:
torch.cat((X,Y),dim=1) # concatenate by col

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [28]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [29]:
X.sum()

tensor(66.)

In [30]:
# Broadcasting Mechanish: operations on tensors of different shape

In [31]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b # a is 3 X 1, b is 1 X 2

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
# Since a and b are  3×1  and  1×2  matrices respectively, 
# their shapes do not match up if we want to add them. 
# We broadcast the entries of both matrices into a larger  
# 3×2  matrix as follows: for matrix a it replicates the 
# columns and for matrix b it replicates the rows before 
# adding up both elementwise.

In [33]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [34]:
# indexing and slicing. like python array the end point is not included
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [35]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [36]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [37]:
X[1,2] # element in the 1-index row and 2-index %colors

tensor(6.)

In [38]:
# write elements

In [39]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [40]:
X[:2, :] = 1

In [41]:
X

tensor([[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.]])

In [42]:
# saving memory

In [43]:
before = id(Y)

In [44]:
before

1522827679208

In [45]:
Y = Y+X

In [46]:
id(Y) == before

False

In [47]:
before = id(Y)
Y+=X
id(Y) == before

True

In [48]:
before = id(Y)
Y[:] = Y+X
id(Y) == before

True

In [49]:
Y

tensor([[ 5.,  4.,  7.,  6.],
        [ 4.,  5.,  6.,  7.],
        [28., 30., 32., 34.]])

In [50]:
Z = torch.zeros_like(Y)
print(id(Z))
Z[:] = X+Y
print(id(Z))

1522827852920
1522827852920


In [51]:
# Converting to a NumPy tensor, or vice versa, is easy. 
# The converted result does not share memory.

In [52]:
import numpy as np

In [53]:
A = X.numpy()

In [54]:
B = torch.tensor(A)

In [55]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [56]:
a = torch.tensor([3.5])

In [57]:
a

tensor([3.5000])

In [58]:
a.item()

3.5

In [59]:
float(a)

3.5

In [60]:
int(a)

3

In [61]:
b = torch.tensor([3.5, 4.6])

In [62]:
int(b)

ValueError: only one element tensors can be converted to Python scalars

In [63]:
x = torch.arange(12).reshape(3,4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [64]:
x > y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [65]:
x < y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [66]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [67]:
a = torch.arange(5).reshape(5,1)

In [68]:
a

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [69]:
b = torch.tensor([2,3]).reshape(1,2)
b

tensor([[2, 3]])

In [70]:
b.shape

torch.Size([1, 2])

In [71]:
a + b

tensor([[2, 3],
        [3, 4],
        [4, 5],
        [5, 6],
        [6, 7]])